# Generated by Django 3.0.7 on 2020-06-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_pic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
